version: '3.7'
services:
    postgres:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        volumes:
        - ./volumes/postgres/:/var/lib/postgresql/data/
    
    postgraphile:
        image: stephaneklein/poc-postgraphile-react-upload-to-s3:latest
        ports:
          - 5000:5000
        environment:
          GRAPHQL_API_DATABASE_STRING_URL: postgres://postgres:password@postgres:5432/postgres
          GRAPHQL_API_S3_ATTACHMENTS_ENABLE: 1
          GRAPHQL_API_S3_ATTACHMENTS_ENDPOINT: s3
    
    s3:
        image: minio/minio:RELEASE.2020-04-23T00-58-49Z
        environment:
          MINIO_ACCESS_KEY: admin
          MINIO_SECRET_KEY: password
        ports:
          - "9000:9000"
        volumes:
          - ./volumes/minio/:/data
        entrypoint: sh
        command: >
            -c 'mkdir -p /data/attachments/ && /usr/bin/minio server /data'